
import { InboundRecord } from "@/types";

export const generateMockData = (): InboundRecord[] => {
  const records: InboundRecord[] = [
    {
      id: "1",
      customerRecordId: "CR-001",
      firstName: "John",
      lastName: "Doe",
      address: "123 Apple St",
      city: "Cupertino",
      state: "CA",
      zip: "95014",
      phone: "(408) 555-1234",
      product: "MacBook Pro",
      email: "john.doe@example.com",
      sender: "Website",
      received: "2023-07-15T14:30:00",
      source: "Online",
      subSource: "Product Page",
      market: "Tech",
      notes: "Interested in the new M2 model",
      checkOutDate: null,
      checkedOutBy: null,
    },
    {
      id: "2",
      customerRecordId: "CR-002",
      firstName: "Jane",
      lastName: "Smith",
      address: "456 Pixel Ave",
      city: "San Francisco",
      state: "CA",
      zip: "94105",
      phone: "(415) 555-6789",
      product: "iPhone 14 Pro",
      email: "jane.smith@example.com",
      sender: "Mobile App",
      received: "2023-07-15T15:45:00",
      source: "Mobile",
      subSource: "iOS App",
      market: "Consumer",
      notes: "Requesting more information about trade-in options",
      checkOutDate: "2023-07-15T16:30:00",
      checkedOutBy: "Alex Johnson",
    },
    {
      id: "3",
      customerRecordId: "CR-003",
      firstName: "Robert",
      lastName: "Johnson",
      address: "789 Silicon Dr",
      city: "Palo Alto",
      state: "CA",
      zip: "94301",
      phone: "(650) 555-4321",
      product: "iPad Air",
      email: "robert.j@example.com",
      sender: "Partner Referral",
      received: "2023-07-15T16:15:00",
      source: "Partner",
      subSource: "Best Buy",
      market: "Education",
      notes: "Looking for education discount for university purchase",
      checkOutDate: null,
      checkedOutBy: null,
    },
    {
      id: "4",
      customerRecordId: "CR-004",
      firstName: "Emily",
      lastName: "Wilson",
      address: "321 Tech Blvd",
      city: "San Jose",
      state: "CA",
      zip: "95110",
      phone: "(408) 555-8765",
      product: "Apple Watch Series 8",
      email: "emily.w@example.com",
      sender: "Email Campaign",
      received: "2023-07-15T17:00:00",
      source: "Email",
      subSource: "Newsletter",
      market: "Health",
      notes: "Interested in health tracking features",
      checkOutDate: null,
      checkedOutBy: null,
    },
    {
      id: "5",
      customerRecordId: "CR-005",
      firstName: "Michael",
      lastName: "Brown",
      address: "654 Innovation Way",
      city: "Mountain View",
      state: "CA",
      zip: "94043",
      phone: "(650) 555-1122",
      product: "AirPods Pro",
      email: "michael.b@example.com",
      sender: "Social Media",
      received: "2023-07-15T17:30:00",
      source: "Social",
      subSource: "Instagram",
      market: "Entertainment",
      notes: "Question about noise cancellation feature",
      checkOutDate: "2023-07-15T18:15:00",
      checkedOutBy: "Sarah Parker",
    },
    {
      id: "6",
      customerRecordId: "CR-006",
      firstName: "Jessica",
      lastName: "Garcia",
      address: "987 Design Ln",
      city: "Berkeley",
      state: "CA",
      zip: "94704",
      phone: "(510) 555-3344",
      product: "Mac Studio",
      email: "jessica.g@example.com",
      sender: "Retail Store",
      received: "2023-07-15T18:00:00",
      source: "Retail",
      subSource: "Berkeley Store",
      market: "Creative",
      notes: "Professional video editor looking for high-performance option",
      checkOutDate: null,
      checkedOutBy: null,
    },
    {
      id: "7",
      customerRecordId: "CR-007",
      firstName: "David",
      lastName: "Lee",
      address: "753 Cloud St",
      city: "Santa Clara",
      state: "CA",
      zip: "95051",
      phone: "(408) 555-5566",
      product: "iCloud+ Subscription",
      email: "david.l@example.com",
      sender: "Customer Service",
      received: "2023-07-15T18:30:00",
      source: "Support",
      subSource: "Chat",
      market: "Services",
      notes: "Needs help with storage upgrade options",
      checkOutDate: null,
      checkedOutBy: null,
    },
    {
      id: "8",
      customerRecordId: "CR-008",
      firstName: "Sophia",
      lastName: "Martinez",
      address: "246 Infinity Loop",
      city: "Sunnyvale",
      state: "CA",
      zip: "94087",
      phone: "(408) 555-7788",
      product: "Apple TV 4K",
      email: "sophia.m@example.com",
      sender: "Website",
      received: "2023-07-15T19:00:00",
      source: "Online",
      subSource: "Accessories Page",
      market: "Home",
      notes: "Comparing different Apple TV models",
      checkOutDate: null,
      checkedOutBy: null,
    },
    {
      id: "9",
      customerRecordId: "CR-009",
      firstName: "William",
      lastName: "Taylor",
      address: "135 Logic Ave",
      city: "Oakland",
      state: "CA",
      zip: "94612",
      phone: "(510) 555-9900",
      product: "HomePod Mini",
      email: "william.t@example.com",
      sender: "Partner Referral",
      received: "2023-07-15T19:30:00",
      source: "Partner",
      subSource: "Target",
      market: "Smart Home",
      notes: "Interested in multi-room audio setup",
      checkOutDate: "2023-07-15T20:15:00",
      checkedOutBy: "James Wilson",
    },
    {
      id: "10",
      customerRecordId: "CR-010",
      firstName: "Olivia",
      lastName: "Anderson",
      address: "864 Developer Dr",
      city: "Fremont",
      state: "CA",
      zip: "94539",
      phone: "(510) 555-1212",
      product: "Final Cut Pro",
      email: "olivia.a@example.com",
      sender: "Email Campaign",
      received: "2023-07-15T20:00:00",
      source: "Email",
      subSource: "Promo",
      market: "Software",
      notes: "Student looking for educational pricing on software",
      checkOutDate: null,
      checkedOutBy: null,
    }
  ];
  
  return records;
};

export const addNewRecord = (
  records: InboundRecord[],
  setRecords: React.Dispatch<React.SetStateAction<InboundRecord[]>>
) => {
  const firstNames = ["Emma", "Noah", "Ava", "Liam", "Sophia", "Mason", "Isabella", "Jacob", "Olivia", "William"];
  const lastNames = ["Johnson", "Williams", "Jones", "Brown", "Davis", "Miller", "Wilson", "Moore", "Taylor", "Anderson"];
  const cities = ["San Francisco", "Los Angeles", "San Diego", "Sacramento", "Fresno", "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Santa Ana"];
  const products = ["iPhone 14", "MacBook Air", "iPad Pro", "Apple Watch", "AirPods", "Mac Mini", "iMac", "Studio Display", "Magic Keyboard", "Apple Pencil"];
  const sources = ["Online", "Retail", "Partner", "Email", "Social", "Mobile", "Support", "Event", "Referral", "Direct"];
  
  const randomItem = (array: string[]) => array[Math.floor(Math.random() * array.length)];
  
  const newRecord: InboundRecord = {
    id: `${records.length + 1}`,
    customerRecordId: `CR-${String(records.length + 11).padStart(3, '0')}`,
    firstName: randomItem(firstNames),
    lastName: randomItem(lastNames),
    address: `${Math.floor(Math.random() * 1000) + 1} ${randomItem(["Oak", "Pine", "Maple", "Cedar", "Elm"])} ${randomItem(["St", "Ave", "Blvd", "Dr", "Ct"])}`,
    city: randomItem(cities),
    state: "CA",
    zip: `9${Math.floor(Math.random() * 10000).toString().padStart(4, '0')}`,
    phone: `(${Math.floor(Math.random() * 800) + 200}) 555-${Math.floor(Math.random() * 10000).toString().padStart(4, '0')}`,
    product: randomItem(products),
    email: `${randomItem(firstNames).toLowerCase()}.${randomItem(lastNames).toLowerCase()}@example.com`,
    sender: randomItem(["Website", "Mobile App", "Email Campaign", "Partner Referral", "Social Media"]),
    received: new Date().toISOString(),
    source: randomItem(sources),
    subSource: randomItem(["Product Page", "Store", "Newsletter", "Instagram", "Facebook", "Twitter", "Chat", "Call Center"]),
    market: randomItem(["Consumer", "Education", "Business", "Healthcare", "Creative", "Enterprise"]),
    notes: randomItem([
      "Interested in financing options",
      "Looking for business volume discount",
      "Has questions about AppleCare+",
      "Requesting product comparison",
      "Needs technical specifications",
      "Wants to know about availability",
      "Asking about shipping times",
      "Interested in trade-in value"
    ]),
    checkOutDate: null,
    checkedOutBy: null,
    isNew: true
  };
  
  setRecords([newRecord, ...records]);
  
  // Remove the 'isNew' flag after animation
  setTimeout(() => {
    setRecords(prevRecords => 
      prevRecords.map(record => 
        record.id === newRecord.id ? { ...record, isNew: false } : record
      )
    );
  }, 2000);
};
